all: build_read_write_without_priority

build_read_write_without_priority: 
	gcc read_write_without_priority.c -o without_priority -Wall -lpthread

debug_read_write_without_priority:
	gcc -g debug_read_write_without_priority.c -o debug_without_priority -Wall -lpthread -lm