all: ReadWriteWithSemaphores ReadWriteWithSemaphoresAndLocks

ReadWriteWithSemaphores:
	gcc ReadWriteWithSemaphores.c -o ReadWriteWithSemaphores -Wall -lpthread -lm

ReadWriteWithSemaphoresAndLocks:
	gcc ReadWriteWithSemaphoresAndLocks.c -o ReadWriteWithSemaphoresAndLocks -Wall -lpthread -lm
